### ISSUE TITLE
format of 'from' on import statement

### ISSUE THREAD

**Issue by ckross01** [Icehunter/language-jsx#2]
The from in an import statement isn't stylized in .jsx files
<img width="176" alt="screen shot 2015-10-09 at 4 43 38 pm" src="https://cloud.githubusercontent.com/assets/1379666/10405145/0c5ffd96-6ea5-11e5-91b2-27e36dd07e98.png">

Wasn't sure if that was on purpose or if you would be ok with having it purple also, believe other js addons style it the same.

<img width="204" alt="screen shot 2015-10-09 at 4 41 23 pm" src="https://cloud.githubusercontent.com/assets/1379666/10405108/d11fc05e-6ea4-11e5-82dc-44f76c359e8b.png">

If the purple on 'from' is ok let me know and I'll get a pr together.

**Comment by Icehunter** [comment]
That would be great :)
